config/routes.rb
# == Route Map
#
#                    Prefix Verb URI Pattern                                                                              Controller#Action
#                      root GET  /                                                                                        users#new
#                user_works GET  /users/:user_id/works(.:format)                                                          works#index
#                           POST /users/:user_id/works(.:format)                                                          works#create
#             new_user_work GET  /users/:user_id/works/new(.:format)                                                      works#new
#              user_healths GET  /users/:user_id/healths(.:format)                                                        healths#index
#                           POST /users/:user_id/healths(.:format)                                                        healths#create
#           new_user_health GET  /users/:user_id/healths/new(.:format)                                                    healths#new
#            user_calenders GET  /users/:user_id/calenders(.:format)                                                      calenders#index
#                     users POST /users(.:format)                                                                         users#create
#              check_points GET  /modes/:id/check_points(.:format)                                                        check_points#index
#                           POST /modes/:id/check_points(.:format)                                                        check_points#create
#           new_check_point GET  /modes/:id/check_points/new(.:format)                                                    check_points#new
#                     modes GET  /modes(.:format)                                                                         modes#index
#        rails_service_blob GET  /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET  /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET  /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT  /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root to: "users#new"

  resources :users, only: [:create] do
    resources :works, only: [:index, :new, :create]
    resources :healths, only: [:index, :new, :create]
    resources :calenders, only: [:index]
  end

  resources :modes, only: [:index] do
    member do
      resources :check_points, only: [:index, :new, :create]
    end
  end

  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/health.rb
class Health < ApplicationRecord
  belongs_to :user
end

app/controllers/healths_controller.rb
class HealthsController < AuthController

  before_action :check_user

  def index
  end

  def new
    @health = ::Health.new
  end

  def create
    @health = ::Health.new(health_params)
    if @health.save
      flash[:notice] = "登録しました"
      redirect_to user_works_path(user_id: @current_user.custom_url)
    else
      render :new
    end
  end

  private

  def health_params
    params.require(:health).permit(:weight, :metabolism, :muscle, :fat_rate).tap do |v|
      v[:user_id] = @current_user.id
    end
  end
end

app/views/healths/index.html.erb
<h1>Weights#index</h1>
<p>Find me in app/views/weights/index.html.erb</p>

app/views/healths/new.html.erb
<%= stylesheet_link_tag    "users_new", media: 'all', 'data-turbolinks-track': 'reload' %>
<% if @health.errors.full_messages.present? %>
  <% @health.errors.full_messages.each do |message| %>
    <p class="error_message"><%= message %></p>
  <% end %>
<% end %>
<%= form_for @health, url: user_healths_path(user_id: @current_user.custom_url)  do |f| %>
  <div class="input">
    <label class="input_label">体重(kg)</label>
    <%= f.number_field :weight, step: 0.01 %>
  </div>

  <div class="input">
    <label class="input_label">基礎代謝(kcal)</label>
    <%= f.number_field :metabolism, step: 0.01 %>
  </div>

  <div class="input">
    <label class="input_label">筋肉量</label>
    <%= f.number_field :muscle, step: 0.01 %>
  </div>

  <div class="input">
    <label class="input_label">体脂肪率(パーセント)</label>
    <%= f.number_field :fat_rate, step: 0.01 %>
  </div>

  <div class="submit">
    <%= submit_tag "OK", class: "btn btn-primary" %>
  </div>
<% end %>