config/routes.rb
# == Route Map
#
#                    Prefix Verb URI Pattern                                                                              Controller#Action
#                      root GET  /                                                                                        users#new
#                user_works GET  /users/:user_id/works(.:format)                                                          works#index
#                           POST /users/:user_id/works(.:format)                                                          works#create
#             new_user_work GET  /users/:user_id/works/new(.:format)                                                      works#new
#              user_healths GET  /users/:user_id/healths(.:format)                                                        healths#index
#                           POST /users/:user_id/healths(.:format)                                                        healths#create
#           new_user_health GET  /users/:user_id/healths/new(.:format)                                                    healths#new
#            user_calenders GET  /users/:user_id/calenders(.:format)                                                      calenders#index
#                     users POST /users(.:format)                                                                         users#create
#              check_points GET  /modes/:id/check_points(.:format)                                                        check_points#index
#                           POST /modes/:id/check_points(.:format)                                                        check_points#create
#           new_check_point GET  /modes/:id/check_points/new(.:format)                                                    check_points#new
#                     modes GET  /modes(.:format)                                                                         modes#index
#        rails_service_blob GET  /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET  /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET  /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT  /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root to: "users#new"

  resources :users, only: [:create] do
    resources :works, only: [:index, :new, :create]
    resources :healths, only: [:index, :new, :create]
    resources :calenders, only: [:index]
  end

  resources :modes, only: [:index] do
    member do
      resources :check_points, only: [:index, :new, :create]
    end
  end

  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/check_point.rb
class CheckPoint < ApplicationRecord
  belongs_to :mode

  validates :dist, presence: true
  validates :start_point, presence: true
end

app/controllers/check_points_controller.rb
class CheckPointsController < ApplicationController
  def index
    @check_points = CheckPoint.where(mode_id: params[:id]).order(:dist)
  end

  def new
    @check_points = CheckPoint.where(mode_id: params[:id]).order(:dist).to_a
    5.times do |i|
      @check_points.append(CheckPoint.new(mode_id: params[:id]))
    end
  end

  def create
    @check_points = params[:check_points].map do |v|
      cp = CheckPoint.new(
        mode_id: v[:mode_id],
        start_point: v[:start_point],
        dist: v[:dist]
      )
      next if cp.start_point.blank? || cp.dist.blank?
      cp
    end
    @check_points.compact!
    p @check_points
    ActiveRecord::Base.transaction do
      CheckPoint.where(mode_id: params[:id]).destroy_all
      CheckPoint.import! @check_points
    end
      redirect_to  new_check_point_path(id: params[:id])
  rescue ActiveRecord::RecordInvalid
      render "new"
  end



end

app/views/check_points/index.html.erb
<%= stylesheet_link_tag    "check_points_index", media: 'all', 'data-turbolinks-track': 'reload' %>

<ul>
<% @check_points.each do |cp| %>
  <li>
    <span class="id"><%= cp.id %></span>
    <span class="start_point">
      <%= cp.start_point %>
    </span>
    <span class="dist"><%= cp.dist %>km</span>
  <li>
<% end %>
</ul>

app/views/check_points/new.html.erb
<%= stylesheet_link_tag    "check_points_new", media: 'all', 'data-turbolinks-track': 'reload' %>

<%= form_tag(check_points_path) do %>
  <ul>
    <% @check_points.each do |cp| %>
      <li>
        <%= text_field_tag "check_points[][mode_id]", cp.mode_id, style: "display: none" %>
        <span class="id">
          <%= text_field_tag "check_points[][id]", cp.id %>
        </span>
        <span class="start_point">
          <%= text_field_tag "check_points[][start_point]", cp.start_point %>
        </span>
        <span class="dist">
          <%= text_field_tag "check_points[][dist]", cp.dist %>
        </span>
      </li>
    <% end %>
  </ul>
  <%= submit_tag "submit" %>
<% end %>