config/routes.rb
# == Route Map
#
#                    Prefix Verb URI Pattern                                                                              Controller#Action
#                      root GET  /                                                                                        users#new
#                user_works GET  /users/:user_id/works(.:format)                                                          works#index
#                           POST /users/:user_id/works(.:format)                                                          works#create
#             new_user_work GET  /users/:user_id/works/new(.:format)                                                      works#new
#              user_healths GET  /users/:user_id/healths(.:format)                                                        healths#index
#                           POST /users/:user_id/healths(.:format)                                                        healths#create
#           new_user_health GET  /users/:user_id/healths/new(.:format)                                                    healths#new
#            user_calenders GET  /users/:user_id/calenders(.:format)                                                      calenders#index
#                     users POST /users(.:format)                                                                         users#create
#              check_points GET  /modes/:id/check_points(.:format)                                                        check_points#index
#                           POST /modes/:id/check_points(.:format)                                                        check_points#create
#           new_check_point GET  /modes/:id/check_points/new(.:format)                                                    check_points#new
#                     modes GET  /modes(.:format)                                                                         modes#index
#        rails_service_blob GET  /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET  /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET  /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT  /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root to: "users#new"

  resources :users, only: [:create] do
    resources :works, only: [:index, :new, :create]
    resources :healths, only: [:index, :new, :create]
    resources :calenders, only: [:index]
  end

  resources :modes, only: [:index] do
    member do
      resources :check_points, only: [:index, :new, :create]
    end
  end

  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RunDist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <% view_name = "#{controller.controller_name}_#{controller.action_name}" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'common', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% page_titles = {
      "users_new": "ユーザー登録",
      "users_create": "ユーザー登録",
      "works_index": "サマリー",
      "works_new": "記録",
      "works_create": "記録",
      "modes_index": "モード一覧",
      "calenders_index": "カレンダー"
    }
    %>
      <div class="header-info" >
        <h1>
          <% if @current_user %>
            <%= link_to "ハシッタ君", user_works_path(user_id: @current_user.custom_url)%>
          <% else %>
            ハシッタ君
          <% end %>
        </h1>
        <p class="page_title">
          <% if @current_user && ["users", "works", "calenders"].include?(controller.controller_name) %>
            <%= link_to "サマリー", user_works_path(user_id: @current_user.custom_url) %>
            <%= link_to "カレンダー", user_calenders_path(user_id: @current_user.custom_url) %>
          <% end %>
        </p>
      </div>
      <div class="header-menu">
        <ul>
          <% if @current_user && ["users", "works", "calenders"].include?(controller.controller_name) %>
            <li class="btn btn-primary link_wrap">
              <%= link_to "+走行距離", new_user_work_path(user_id: @current_user.custom_url) %>
            </li>
            <li class="btn btn-primary link_wrap">
              <%= link_to "+体重", new_user_health_path(user_id: @current_user.custom_url) %>
            </li>
          <% end %>
        </ul>
      </div>
    </header>
    
    <% if flash[:notice].present? %>
      <p class="notice_message"><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>